### PR TITLE
fix growable list

### PR DESCRIPTION
**Pull request by rmasarovic**

### CODE REVIEW

**Comment by AlvinRamoutar** [comment]
Hey @rmasarovic ,

Looks good to me! While you're fixing this, mind also updating the following list as well to be `growable` ?
https://github.com/AlvinRamoutar/sudoku-api/blob/7801b91ec9ae94cadb54967234fe423c3b178c3e/lib/src/models/PatternSet.dart#L121

Thanks!
Alvin

**Comment by rmasarovic** [comment]
Hi yes you are right.  I fixed this and wrote test for this error validation.
Check this.

**Comment by AlvinRamoutar** [comment]
Hey @rmasarovic ,

Love the addition of that test, thank you!

Just some minor spelling/formatting fixes, mind updating your function as follows please?

```dart
  String patternSetTest = 'Test invalid pattern set';
  test(patternSetTest, () {
    final Map<int, String> errorMap = {
      0: "0 0 0 0 1 0 0 0 0 1 0",
    };
    final patternSet = PatternSet();
    final patternName = "errorPattern";

    Pattern pattern = Pattern(patternName, errorMap);
    expect(
        () => patternSet.add(pattern), throwsA(isA<InvalidPatternException>()));
  });
```

**Comment by hadycodes** [comment]
@AlvinRamoutar can we merge this please :)

**Comment by AlvinRamoutar** [comment]
Hey @HadiIOS / @rmasarovic ,
Sorry for the delay, will integrate it this week.
Thanks for keeping me in check :)
Alvin

**Comment by AlvinRamoutar** [comment]
LGTM - will take care of formatting.

**Comment by AlvinRamoutar** [comment]
Released in 2.1.0

**Pull request merged**
